/**
 * analyze.ts - TypeScript caller for the Python text-analysis bridge.
 *
 * This file calls analyze.py via Stitch.
 * The bridge files (.stitch/bridges/text_analyzer.ts and .py)
 * are generated by Claude Code - see README.md for the command.
 */

import { readFileSync } from "fs";
import * as path from "path";

import { PythonBridge as TextAnalyzerBridge } from "./.stitch/bridges/text_analyzer.js";

async function main() {
  const samplePath = path.join(import.meta.dirname, "data", "sample.txt");
  const text = readFileSync(samplePath, "utf8");

  // ── After Stitch generates the files, use this: ─────────────────────

  const sidecarPath = path.join(import.meta.dirname, ".stitch", "bridges", "text_analyzer.py");
  const bridge = new TextAnalyzerBridge(sidecarPath);
  await bridge.start();

  try {
    const stats    = await bridge.summarize(text);
    const topWords = await bridge.topWords(text, 8);

    console.log("═".repeat(50));
    console.log("  Text Analysis Report");
    console.log("═".repeat(50));
    console.log(`  Words          : ${stats.word_count}`);
    console.log(`  Sentences      : ${stats.sentence_count}`);
    console.log(`  Unique words   : ${stats.unique_words}`);
    console.log(`  Readability    : ${stats.readability_score} / 100`);
    console.log(`  Top words      : ${topWords.top_words.map(([w]) => w).join(", ")}`);
    console.log("═".repeat(50));
  } finally {
    await bridge.stop();
  }

  // ─────────────────────────────────────────────────────────────────────────
}

main().catch(console.error);
