/**
 * server.ts - Express server for the face-recognition app.
 *
 * POST /api/analyze  - accepts { image_b64: string } (JPEG, base64-encoded)
 *                      returns { faces: Array<{x,y,w,h,confidence}> }
 *
 * The Python face-detection bridge is generated by Stitch.
 * See README.md for the exact Claude Code prompt.
 *
 * Before the bridge exists the endpoint returns a static placeholder so the
 * UI starts up cleanly even without the Python sidecar.
 */

import express, { Request, Response } from "express";
import * as path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ── Bridge import (populated by Stitch) ─────────────────────────────────
// After running the MCP tool this import resolves to the generated bridge.
// Until then the server falls back to the stub below.
let bridge: FaceDetectionBridge | null = null;

interface FaceDetectionBridge {
  start(): Promise<void>;
  stop(): Promise<void>;
  analyzeFrame(params: { image_b64: string }): Promise<{
    faces: { x: number; y: number; w: number; h: number; confidence: number }[];
  }>;
}

async function loadBridge(): Promise<void> {
  try {
    const mod = await import(
      "./.stitch/bridges/face_detector.js" as string
    );
    const b: FaceDetectionBridge = new mod.PythonBridge(
      path.join(__dirname, ".stitch", "bridges", "face_detector.py"),
    );
    await b.start();
    bridge = b;
    console.log("[bridge] Python face-detection sidecar started.");
  } catch {
    console.warn(
      "[bridge] face_detector bridge not found - run Stitch first (see README).",
    );
    console.warn("[bridge] Serving placeholder responses until bridge loads.");
  }
}

// ── Express setup ─────────────────────────────────────────────────────────────

const app = express();
app.use(express.json({ limit: "4mb" }));
app.use(express.static(path.join(__dirname, "public")));

// ── POST /api/analyze ─────────────────────────────────────────────────────────

app.post(
  "/api/analyze",
  async (req: Request, res: Response): Promise<void> => {
    const { image_b64 } = req.body as { image_b64?: string };

    if (!image_b64) {
      res.status(400).json({ error: "Missing image_b64" });
      return;
    }

    if (!bridge) {
      // Stub: return empty faces list so the UI still renders.
      res.json({ faces: [], stub: true });
      return;
    }

    try {
      const result = await bridge.analyzeFrame({ image_b64 });
      res.json(result);
    } catch (err) {
      console.error("[bridge] analyzeFrame error:", err);
      res.status(500).json({ error: String(err) });
    }
  },
);

// ── Startup ───────────────────────────────────────────────────────────────────

const PORT = Number(process.env.PORT ?? 3000);

await loadBridge();

const server = app.listen(PORT, () => {
  console.log(`[server] Listening on http://localhost:${PORT}`);
});

process.on("SIGINT", async () => {
  console.log("\n[server] Shutting down…");
  server.close();
  if (bridge) await bridge.stop();
  process.exit(0);
});
